avance/config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get 'avance/home'

  get 'avance/donates'

  get 'avance/login'

  resources :cadastro_menors

   root 'avance#home'

    get '/cadastro' => 'cadastro_menors#index'
    get '/login' => 'avance#login'
    get '/donates' => 'avance#donates'
    get '/home' => 'avance#home'

end

avance/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
   if user.has_role? :admin
     can :manage, :all
   elsif user.has_role? :author
     can :create, Status # author can create status
     can :update, Status # author can update status
     # can :destroy, Status # #uncomment this line, author can destroy status
     can :read, :all
   else
     can :read, :all
   end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

avance/app/models/cadastro_menor.rb
class CadastroMenor < ActiveRecord::Base
    validates_presence_of :Nome, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Data_de_Nascimento, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Sexo, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Naturalidade, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Filiação, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Nome_Responsavel, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :RG, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :CPF, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Estado_Civil, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Profissão, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Instrução, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Renda_Familiar, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Endereço_atual, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Cidade, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Telone, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Moradia, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Descrição_acidente, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Agente_Causador, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Queimadura, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Região_Atingida, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Sequela, :on => :create, :message => "Campo Obrigatório"
    validates_presence_of :Data_Acidente, :on => :create, :message => "Campo Obrigatório"
end

avance/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         ROLES = %i[admin author]

 def roles=(roles)
   roles = [*roles].map { |r| r.to_sym }
   self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
 end

 def roles
   ROLES.reject do |r|
     ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
   end
 end

 def has_role?(role)
   roles.include?(role)
 end
 
end

avance/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up)  { |u| u.permit(  :email,:password, :password_confirmation, roles: []) }
 end
 
end

avance/app/controllers/avance_controller.rb
class AvanceController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def home
  end

  def donates
  end

  def login
  end
end

avance/app/controllers/cadastro_menors_controller.rb
class CadastroMenorsController < ApplicationController

  before_action :set_cadastro_menor, only: [:show, :edit, :update, :destroy]

  # GET /cadastro_menors
  # GET /cadastro_menors.json
  def index
    @cadastro_menors = CadastroMenor.all
  end

  # GET /cadastro_menors/1
  # GET /cadastro_menors/1.json
  def show
  end

  # GET /cadastro_menors/new
  def new
    @cadastro_menor = CadastroMenor.new
  end

  # GET /cadastro_menors/1/edit
  def edit
  end

  # POST /cadastro_menors
  # POST /cadastro_menors.json
  def create
    @cadastro_menor = CadastroMenor.new(cadastro_menor_params)

    respond_to do |format|
      if @cadastro_menor.save
        format.html { redirect_to @cadastro_menor, notice: 'Cadastro foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @cadastro_menor }
      else
        format.html { render :new }
        format.json { render json: @cadastro_menor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastro_menors/1
  # PATCH/PUT /cadastro_menors/1.json
  def update
    respond_to do |format|
      if @cadastro_menor.update(cadastro_menor_params)
        format.html { redirect_to @cadastro_menor, notice: 'Cadastro foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cadastro_menor }
      else
        format.html { render :edit }
        format.json { render json: @cadastro_menor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastro_menors/1
  # DELETE /cadastro_menors/1.json
  def destroy
    @cadastro_menor.destroy
    respond_to do |format|
      format.html { redirect_to cadastro_menors_url, notice: 'Cadastro foi deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_menor
      @cadastro_menor = CadastroMenor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_menor_params
      params.require(:cadastro_menor).permit(:Nome, :Data_de_Nascimento, :Sexo, :Idade, :Naturalidade, :Filiação, :Nome_Responsavel, :RG, :CPF, :Estado_Civil, :Profissão, :Instrução, :Endereço_atual, :Cidade, :Telone, :Moradia, :Renda_Familiar, :Descrição_acidente, :Agente_Causador, :Queimadura, :Região_Atingida, :Sequela, :Data_Acidente, :Brasilia_DF)
    end
end

avance/app/helpers/application_helper.rb
module ApplicationHelper
end

avance/app/helpers/avance_helper.rb
module AvanceHelper
end

avance/app/helpers/cadastro_menors_helper.rb
module CadastroMenorsHelper
end

avance/app/views/avance/donates.html.erb
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
      <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <%= link_to "Avance", '/', id: "logo" %>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home",   '/' %></li>
              <li><%= link_to "Doações",   '/donates' %></li>
              <li><%= link_to "Login", '/login' %></li>
            </ul>
          </nav>
        </div>
      </header>

    <div class="container">
      Para Doar Vá para o HRAN e procure a avance ou ligue no numero 83245236
    </div>
  </body>

avance/app/views/avance/home.html.erb
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container" class="nav-wrapper">
        <%= link_to "Avance", '/', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right" id="nav-mobile" class="right hide-on-med-and-down">
              <li><a href="/">Home</a></li>
              <li><a href="/donates">Doações</a></li>
              <li><a href="/login">Login</a></li>
          </ul>
        </nav>
      </div>
    </header>
    <!%= link_to image_tag("avance.png" alt: "Avance logo"),
    'https://pt-br.facebook.com/avancebr/' %>
    <!img alt="Avance logo" src="avance.png" height="60" width="60">

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

avance/app/views/avance/login.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>
<head>
  <%= stylesheet_link_tag 'application', media: 'all',
                                         'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Avance", '/', id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   '/' %></li>
          <li><%= link_to "Doações",   '/donates' %></li>
        </ul>
      </nav>
    </div>
  </header>
  <!%= link_to image_tag("avance.png" alt: "Avance logo"),
  'https://pt-br.facebook.com/avancebr/' %>
  <!img alt="Avance logo" src="avance.png" height="60" width="60">

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:session, url: login_path) do |f| %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :senha %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.submit "Entrar", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</body>

avance/app/views/cadastro_menors/_form.html.erb
<%= form_for(@cadastro_menor) do |f| %>
  <% if @cadastro_menor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cadastro_menor.errors.count, "error") %> prohibited this cadastro_menor from being saved:</h2>

      <ul>
      <% @cadastro_menor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <table>
      <tr>
        <th WIDTH=200><%= f.label :Nome %></th>
        <th WIDTH=230><%= f.label :Data_de_Nascimento %></th><br>
        <th WIDTH=100><%= f.label :Sexo %><br></th>
        <th WIDTH=200><%= f.label :Naturalidade %><br></th>
        <th WIDTH=230><%= f.label :Filiação %><br></th><br>
        <th WIDTH=200></th>
    </tr>
    <tr>
        <th WIDTH=200><%= f.text_field :Nome %></th>
        <th WIDTH=230><%= f.date_select :Data_de_Nascimento, :start_year => Time.now.year - 80, :end_year => Time.now.year%></th>
        <th WIDTH=100><%= f.check_box :Sexo %></th>
        <th WIDTH=200><%= f.text_field :Naturalidade %></th>
        <th WIDTH=230><%= f.text_field :Filiação %></th>
        <th WIDTH=200></th>
    </tr>

    <tr>
      <th WIDTH=200><%= f.label :Nome_Responsavel %><br></th>
      <th WIDTH=200><%= f.label :RG %><br></th>
      <th WIDTH=230><%= f.label :CPF %><br></th><br>
    </tr>
    <tr>
        <th WIDTH=200><%= f.text_field :Nome_Responsavel %></th>
        <th WIDTH=200><%= f.text_field :RG %></th>
        <th WIDTH=230><%= f.text_field :CPF %></th>
    </tr>
    <tr>
      <th WIDTH=200><%= f.label :Estado_Civil %><br></th>
      <th WIDTH=230><%= f.label :Profissão %><br></th><br>
      <th WIDTH=200><%= f.label :Instrução %><br></th>
      <th WIDTH=230><%= f.label :Renda_Familiar %><br></th><br>
    </tr>
    <tr>
        <th WIDTH=200><%= f.text_field :Estado_Civil %></th>
        <th WIDTH=230><%= f.text_field :Profissão %></th>
        <th WIDTH=200><%= f.text_field :Instrução %></th>
        <th WIDTH=230><%= f.text_field :Renda_Familiar %></th>
    </tr>
    <tr>
      <th WIDTH=200><%= f.label :Endereço_atual %><br></th>
      <th WIDTH=230><%= f.label :Cidade %><br></th><br>
      <th WIDTH=200><%= f.label :Telone %><br></th>
      <th WIDTH=200><%= f.label :Moradia %><br></th>
    </tr>
    <tr>
        <th WIDTH=200><%= f.text_field :Endereço_atual %></th>
        <th WIDTH=230><%= f.text_field :Cidade %></th>
        <th WIDTH=200><%= f.text_field :Telone %></th>
        <th WIDTH=200><%= f.text_field :Moradia %></th>
    </tr>
    <tr>
      <th WIDTH=200><%= f.label :Descrição_acidente %><br></th>
      <th WIDTH=230><%= f.label :Agente_Causador %><br></th><br>
      <th WIDTH=200><%= f.label :Queimadura %><br></th>
      <th WIDTH=200><%= f.label :Região_Atingida %><br></th>
      <th WIDTH=100><%= f.label :Sequela %><br></th>
      <th WIDTH=200><%= f.label :Data_Acidente %><br></th>
    </tr>
    <tr>
        <th WIDTH=200><%= f.text_area :Descrição_acidente %></th>
        <th WIDTH=230><%= f.text_field :Agente_Causador %></th>
        <th WIDTH=200><%= f.check_box :Queimadura %></th>
        <th WIDTH=200><%= f.text_field :Região_Atingida %></th>
        <th WIDTH=100><%= f.check_box :Sequela %></th>
        <th WIDTH=200><%= f.date_select :Data_de_Nascimento, :start_year => Time.now.year - 10, :end_year => Time.now.year%></th>
    </tr>
</table>
  <div class="actions">
      <input type="submit" name="commit" value="Cadastrar Paciente" />
  </div>
<% end %>

avance/app/views/cadastro_menors/edit.html.erb
<h1>Editing Cadastro Menor</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @cadastro_menor %> |
<%= link_to 'Voltar', cadastro_menors_path %>

avance/app/views/cadastro_menors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Pacientes</h1>

<table border="1">
  <thead>
    <tr>
      <th WIDTH=150>Nome</th>
      <th WIDTH=150>Data de nascimento</th>
      <th WIDTH=150>Sexo</th>
      <th WIDTH=150>Idade</th>
      <th WIDTH=150 colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastro_menors.each do |cadastro_menor| %>
      <tr>
        <td WIDTH=150><%= cadastro_menor.Nome %></td>
        <td WIDTH=150><%= cadastro_menor.Data_de_Nascimento %></td>
        <td WIDTH=150><%= cadastro_menor.Sexo %></td>
        <td WIDTH=150><%= cadastro_menor.Idade %></td>
        <td WIDTH=150><%= link_to 'Mostrar', cadastro_menor %></td>
        <td WIDTH=150><%= link_to 'Editar', edit_cadastro_menor_path(cadastro_menor) %></td>
        <td WIDTH=150><%= link_to 'Deletar', cadastro_menor, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Paciente', new_cadastro_menor_path %>

avance/app/views/cadastro_menors/new.html.erb
<h1>Novo Paciente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', cadastro_menors_path %>

avance/app/views/cadastro_menors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cadastro_menor.Nome %>
</p>

<p>
  <strong>Data de nascimento:</strong>
  <%= @cadastro_menor.Data_de_Nascimento %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @cadastro_menor.Sexo %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @cadastro_menor.Idade %>
</p>

<p>
  <strong>Naturalidade:</strong>
  <%= @cadastro_menor.Naturalidade %>
</p>

<p>
  <strong>Filiação:</strong>
  <%= @cadastro_menor.Filiação %>
</p>

<p>
  <strong>Nome responsavel:</strong>
  <%= @cadastro_menor.Nome_Responsavel %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @cadastro_menor.RG %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cadastro_menor.CPF %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @cadastro_menor.Estado_Civil %>
</p>

<p>
  <strong>Profissão:</strong>
  <%= @cadastro_menor.Profissão %>
</p>

<p>
  <strong>Instrução:</strong>
  <%= @cadastro_menor.Instrução %>
</p>

<p>
  <strong>Endereço atual:</strong>
  <%= @cadastro_menor.Endereço_atual %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @cadastro_menor.Cidade %>
</p>

<p>
  <strong>Telone:</strong>
  <%= @cadastro_menor.Telone %>
</p>

<p>
  <strong>Moradia:</strong>
  <%= @cadastro_menor.Moradia %>
</p>

<p>
  <strong>Renda familiar:</strong>
  <%= @cadastro_menor.Renda_Familiar %>
</p>

<p>
  <strong>Descrição acidente:</strong>
  <%= @cadastro_menor.Descrição_acidente %>
</p>

<p>
  <strong>Agente causador:</strong>
  <%= @cadastro_menor.Agente_Causador %>
</p>

<p>
  <strong>Queimadura:</strong>
  <%= @cadastro_menor.Queimadura %>
</p>

<p>
  <strong>Região atingida:</strong>
  <%= @cadastro_menor.Região_Atingida %>
</p>

<p>
  <strong>Sequela:</strong>
  <%= @cadastro_menor.Sequela %>
</p>

<p>
  <strong>Data acidente:</strong>
  <%= @cadastro_menor.Data_Acidente %>
</p>

<p>
  <strong>Brasilia df:</strong>
  <%= @cadastro_menor.Brasilia_DF %>
</p>

<%= link_to 'Editar', edit_cadastro_menor_path(@cadastro_menor) %> |
<%= link_to 'Voltar', cadastro_menors_path %>

avance/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= link_to "sign out", destroy_user_session_path, method: : delete %>
  <% end %>
<%= yield %>

</body>
</html>